### ISSUE TITLE
Add GitHub Actions workflow to validate the IDE setup (like devcontainer etc)

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sommerfeld-io/krokidile#28]
Todo ... ChatGPT

```yaml
on:
  push:
    branches-ignore:
      - dependabot/**
    paths:
      - '.devcontainer/**'
    paths-ignore:
      - '**.adoc'
      # all other
```

Run hadolint and docker scout etc.
