### ISSUE TITLE
Introduce a Release Pipeline

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sommerfeld-io/krokidile#6]
- [ ] read version from `package.json` -> somehow determine if a release should be created (is the version the current one or the next one??)
- [ ] Jobs
    - [ ] First
        - [ ] Detect if a release should be created and read current and next version
    - [ ] Then Parallel
        - [ ] Update `antora.yml` and create github release + tag
        - [ ] Deploy to Dockerhub with `README.adoc` contents
    - [ ] Then
        - [ ] Reset `antora.yml` and all other versions if needed
- [ ] Decide whether there should be a dedicated pipeline or whether this should be part of the `pipeline.yml`
- [ ] Write an ADR about standard-version and conventional-commits etc ... (see comments below)
- [ ] Update Commit Message docs - see https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format

**Comment by sebastian-sommerfeld-io** [comment]
i need recommendations from you. i want to release my software from a github actions workflow. that includes

1. detect if a version should be created
2. auto-detect the next version (maybe based on a file in my project)
3. update all version references in my project
4. deploy to dockerhub and create a github release + git tag (in parallel)

how would you do this?

----

Here's a high-level plan for how you could set up your GitHub Actions workflow to automate the release process:

1. **Detect if a version should be created**: You could use a specific keyword in your commit messages to trigger a release. For example, you could decide that any commit message that includes the word "release" should trigger a new version. You can use the `on.push` event in your workflow file to trigger the workflow only when a commit is pushed with a message that includes "release".

2. **Auto-detect the next version**: You could use a tool like `semantic-release` or `standard-version` to automatically determine the next version number based on your commit messages. These tools use the Conventional Commits specification to determine the next semantic version number.

3. **Update all version references in your project**: You can use a tool like `bump2version` or `standard-version` to automatically update all version references in your project.

4. **Deploy to DockerHub and create a GitHub release + git tag**: You can use the `docker/build-push-action` action to build and push your Docker image to DockerHub. You can use the `actions/create-release` action to create a new GitHub release and the `actions/checkout` action to create a new git tag.

Here's a sample workflow file that implements these steps:

```yaml
name: Release Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
    types:
      - 'opened'
      - 'synchronize'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: user/repo:${{ steps.semantic.outputs.new_version }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semantic.outputs.new_version }}
          release_name: Release ${{ steps.semantic.outputs.new_version }}
          draft: false
          prerelease: false
```

This workflow assumes that you're using Node.js and npm in your project. If you're using a different language or package manager, you'll need to adjust the "Setup Node.js" and "Install dependencies" steps accordingly.
